# Site settings 配置站点
title: 'xMinh'
description: '在这里重新开始'
keyword: 'xMinh,Begin Again'
url: 'http://www.xminh.com' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Author 配置博主信息
author: 'xMinh'
nickname: 'Begin Again'
bio: '一枚蒟蒻'
avatar: 'http://wallcoo.com/sport/NBA_San_Antonio_Spurs/wallpapers/1200x900/tie0708_white.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: false
disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'pink'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: 'https://github.com/xMinh'
  weibo: ''
  zhihu: ''
  twitter: ''
  instagrame: ''
  juejin: ''
  douban: ''
  facebook: ''
  dribble: ''
  uicn: ''
  jianshu: ''
  medium: ''
  linkedin: ''

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: false

# Plugins
gems: [jekyll-paginate]
